# docker-compose.yml
version: '3.7'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  job:
    build: ./
    links:
      - redis
    volumes:
      - ./:/var/www/app
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://cache
      - PORT=3000
      - JOB=true
    command:
      sh -c 'npm i && npm run-script watch'

  app:
    build: ./
    links:
      - redis
      - job
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3000
    command:
      sh -c 'npm i && npm run-script watch'
